twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  globals:
    webmaster: "%env(WEBMASTER)%"
    websiteName: "%env(WEBSITE_NAME)%"
    websiteURL: "%env(WEBSITE_URL)%"
    websiteSlogan: "%env(WEBSITE_SLOGAN)%"
